apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "redwine-exp"
  namespace: kserve-inference
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 5
    scaleTarget: 1000
    scaleMetric: concurrency
    serviceAccountName: kserve-sa 
    model:
      modelFormat: 
        name: sklearn
      storageUri: "s3://mlflow/4/ce2903b185a14d4a9fb5abc2a2d106d9/artifacts/model" # change to the S3 URI of your model artifact