apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubeflow
  name: users-kubeflow
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["get", "watch", "list", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users-kubeflow-binding
  namespace: kubeflow
subjects:
- kind: Group
  name: users
roleRef:
  kind: Role
  name: users-kubeflow
  apiGroup: rbac.authorization.k8s.io
