apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mlflow
  name: users-mlflow
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users-mlflow-binding
  namespace: mlflow
subjects:
- kind: Group
  name: users
roleRef:
  kind: Role
  name: users-mlflow
  apiGroup: rbac.authorization.k8s.io
