apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

configMapGenerator:
- name: mlflow-configmap
  env: config.env

secretGenerator:
- name: mlflow-secrets
  envs:
  - secret.env

resources:
  - ./mlflow-namespace.yaml

bases:
  - ./postgres
  - ./minio
  - ./mlflow