apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-minio-storage
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/minio
    type: DirectoryOrCreate