apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: mlflow-minio-pvc
        persistentVolumeClaim:
          claimName: mlflow-minio-pvc
      containers:
      - name: mlflow-minio
        image: minio/minio:RELEASE.2023-02-10T18-48-39Z
        imagePullPolicy: IfNotPresent #Always
        command: [ "/bin/bash" ]
        args: [ "-c", "mkdir -p /data/mlflow  && minio server --address :9000 --console-address :9001 /data" ]
        volumeMounts:
        - name: mlflow-minio-pvc
          mountPath: '/data'
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: mlflow-configmap
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001