- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates 
      - curl 
      - gnupg
      - python3-pip
      - jq
    state: present
    update_cache: yes

- name: Set up Docker repository
  become: true
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    rm /etc/apt/keyrings/docker.gpg
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    update_cache: yes
- name: Create docker group
  group:
    name: docker
    state: present
  become: yes
- name: Add user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes
- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection

- name: Install Kind
  ansible.builtin.shell: |
    [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind

- name: Install kubectl
  ansible.builtin.shell: |
    curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl