apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- kfp-ingress.yaml
- aws-secret.yaml
- github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.8.4
- github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=1.8.4
